id: I08DE24CC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T11:07:01+00:00'
last_modified: '2022-06-07T17:33:34.412720+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9862
  title: གསུང་འབུམ། བློ་བཟང་ཚུལ་ཁྲིམས་བསྟན་པའི་རྒྱལ་མཚན། ༼འབྲས་སྤུངས་པར་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    3FD9:
      image_group_id: I1KG9864
      title: ''
      total_pages: 842
      order: 1
      base_file: 3FD9.txt
    E964:
      image_group_id: I1KG9865
      title: ''
      total_pages: 802
      order: 2
      base_file: E964.txt
    334A:
      image_group_id: I1KG9866
      title: ''
      total_pages: 858
      order: 3
      base_file: 334A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
