id: I08DE24CC
legacy_id: P003100
ocr_import_info:
  bdrc_scan_id: W1KG9862
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T11:00:46'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T18:40:46.304955+00:00'
last_modified: 2022-09-01 02:42:07.933616
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG9862
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG9862
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། བློ་བཟང་ཚུལ་ཁྲིམས་བསྟན་པའི་རྒྱལ་མཚན། ༼འབྲས་སྤུངས་པར་མ།༽
  author: ཏྲེ་ཧོར་ཁང་གསར་བློ་བཟང་ཚུལ་ཁྲིམས་བསྟན་པའི་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.521611394921106
  ocr_word_median_confidence_index: 0.47999998927116394
quality: null
bases:
  I1KG9864:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG9864
      total_pages: 842
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG9864.txt
    statistics:
      ocr_word_median_confidence_index: 0.46000000834465027
      ocr_word_mean_confidence_index: 0.5112597241631505
    legacy_id: v001
  I1KG9865:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG9865
      total_pages: 802
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG9865.txt
    statistics:
      ocr_word_median_confidence_index: 0.49000000953674316
      ocr_word_mean_confidence_index: 0.5259603986600458
    legacy_id: v002
  I1KG9866:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG9866
      total_pages: 858
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG9866.txt
    statistics:
      ocr_word_median_confidence_index: 0.49000000953674316
      ocr_word_mean_confidence_index: 0.528633571210213
    legacy_id: v003
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
